"""
Synthetic burn-in parametric dataset generator for SIH26170.

Produces burn-in electrical measurements at 0/24/96/168 h for N_LOTS x M_PARTS
components, with a hierarchical good-part degradation model, physically
grounded Arrhenius scaling, seven defect/trap archetypes, and explicit
censoring semantics.

--------------------------------------------------------------------------
DESIGN ASSUMPTIONS (stated explicitly; see README for discussion)
--------------------------------------------------------------------------
A1. Cross-parameter correlation is generated by a 2-factor model, not a
    hand-written correlation matrix. Factor 1 is the process/Vth corner
    (fast+leaky vs slow+tight). Factor 2 is a gate-oxide/defect-density
    factor that raises leakage without making the part fast. This
    guarantees a positive-definite correlation matrix and gives every
    correlation a physical name. Resulting corr(iddq, leakage) = +0.91,
    corr(leakage, prop_delay) = -0.75, corr(vth_shift, prop_delay) = +0.73.

A2. `vth_shift_mv` is defined as the measured threshold voltage offset from
    the *design nominal*, not from this part's own 0 h reading. If it were
    defined relative to t=0 it would be identically zero at 0 h for every
    part, which would destroy the cross-sectional joint distribution at the
    first checkpoint. It therefore has a non-degenerate spread at 0 h and a
    positive drift thereafter.

A3. Degradation magnitude is expressed as a fractional drift *per field
    year*, then multiplied by the Arrhenius-equivalent field years of each
    checkpoint. Ea, T_use and T_stress are live inputs: changing them
    changes the dataset. Nothing is hardcoded to AF = 77.7.

A4. Defects are driven by a named *failure mechanism* that selects which
    parameters degrade. A junction-leakage defect moves iddq/leakage/supply
    current; an oxide-trap (NBTI-like) defect moves vth_shift/prop_delay.
    This is more physical than "everything drifts 8x", and it is what makes
    the in-spec constraint satisfiable on tight-margin parameters like
    prop_delay.

A5. Measurement noise sd is 12% of the part-to-part sd (a plausible gauge
    R&R), independent per checkpoint and per parameter.

A6. Beta (the saturating exponent) is fixed per parameter with a small
    per-lot jitter, and lives in [0.5, 1.0] as specified. Physics note: real
    NBTI Vth-shift exponents are nearer 0.15-0.25, so [0.5, 1.0] is a
    deliberately conservative (less strongly saturating) band.

A7. The in-spec constraint is enforced *by construction*: every injected
    offset is scaled down until all measured checkpoints sit inside the
    datasheet limits with a safety margin. Nothing is filtered afterwards.
    The one deliberate exception is the latent 168 h value of a part that
    fails hard and is pulled; that value is out of spec, is never written to
    the measurements file, and is recorded only in ground truth.
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import itertools
import json
import math
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

# --------------------------------------------------------------------------
# Physics
# --------------------------------------------------------------------------

K_BOLTZMANN_EV_PER_K = 8.617e-5   # eV/K
HOURS_PER_YEAR = 8766.0           # 365.25 * 24


def arrhenius_af(ea_ev: float, t_use_c: float, t_stress_c: float) -> float:
    """Arrhenius acceleration factor between a stress and a use temperature.

        AF = exp[ (Ea / k) * (1/T_use - 1/T_stress) ]

    Temperatures are given in Celsius and converted to Kelvin internally.
    Ea in eV, k = 8.617e-5 eV/K.

    Reference check (Part 1.2 of the research doc): Ea=0.7 eV, T_use=55 C,
    T_stress=125 C gives AF = 77.7. That number is *derived here*, never
    hardcoded, so changing Ea or either temperature re-scales the dataset.
    """
    t_use_k = t_use_c + 273.15
    t_stress_k = t_stress_c + 273.15
    return math.exp((ea_ev / K_BOLTZMANN_EV_PER_K) * (1.0 / t_use_k - 1.0 / t_stress_k))


def field_years_equivalent(hours: float, af: float) -> float:
    """Field-use years represented by `hours` of stress at acceleration `af`."""
    return hours * af / HOURS_PER_YEAR


# --------------------------------------------------------------------------
# Parameter specification
# --------------------------------------------------------------------------

@dataclass
class ParamSpec:
    name: str
    unit: str
    v0_mean: float              # population mean of the 0 h value
    v0_sd_part: float           # component-level random effect sd on v0
    v0_sd_lot: float            # lot-level random effect sd on v0
    limit_lo: float             # datasheet lower limit
    limit_hi: float             # datasheet upper limit
    direction: str              # "higher_is_worse" | "two_sided"
    drift_frac_per_field_year: float   # fractional drift per field year
    drift_ref: float            # magnitude the fraction is applied to
    beta: float                 # saturating exponent, 0.5 <= beta <= 1.0
    f1: float                   # loading on factor 1 (process / Vth corner)
    f2: float                   # loading on factor 2 (oxide / defect density)
    phys_floor: float | None = None   # tester measurement floor; strictly
                                      # positive quantities cannot read below it
    log_scale: bool = False           # if True the parameter is LOG-NORMAL:
                                      # v0_mean is read as the median, and
                                      # v0_sd_part / v0_sd_lot as log-scale sds

    @property
    def drift_168_target(self) -> float:
        """Placeholder; the real value is computed by the generator because it
        depends on the Arrhenius settings. Kept as a property for clarity."""
        raise NotImplementedError


def default_params() -> list[ParamSpec]:
    """Five parameters for a mixed digital/analog part.

    Iddq and input leakage are LOG-NORMAL. Real quiescent-current distributions
    are strongly right-skewed -- a lot's worst parts sit several times the lot
    median, not a few percent above it -- and modelling them as Gaussian would
    quietly disarm the robust-statistics argument, because on symmetric data
    mean/sd and median/MAD agree and the breakdown-point distinction stops
    mattering. It also makes the problem statement's own worked example
    (lot averaging ~10 uA, one part at 45 uA, datasheet max 50 uA)
    expressible: that part is a log-normal tail, not a 16-sigma Gaussian event.


    Values are plausible for a screened space-grade CMOS device. The key
    design ratio is drift_at_168h / v0_sd_part ~= 0.70 for every parameter:
    that is what makes a 5-10x drifter land in the 3.5-7 robust-sigma range
    at 168 h, so AEC-Q001 DPAT at 6 sigma catches *some* Type I parts and
    misses others. If drift were tiny relative to part-to-part spread, DPAT
    would catch nothing and the ablation story would be flat; if it were
    huge, DPAT would catch everything and the dataset would be trivial.
    """
    return [
        ParamSpec("iddq_ua", "uA", 12.0, 0.215, 0.170, 0.0, 50.0,
                  "higher_is_worse", 0.0785, 12.0, 0.62, 0.92, 0.30, log_scale=True),
        ParamSpec("leakage_na", "nA", 25.0, 0.235, 0.185, 0.0, 100.0,
                  "higher_is_worse", 0.0940, 25.0, 0.58, 0.94, 0.24, log_scale=True),
        ParamSpec("prop_delay_ns", "ns", 8.00, 0.300, 0.220, 6.0, 10.0,
                  "higher_is_worse", 0.01760, 8.00, 0.70, -0.86, 0.10),
        ParamSpec("supply_current_ma", "mA", 45.0, 3.00, 2.40, 30.0, 65.0,
                  "higher_is_worse", 0.03135, 45.0, 0.66, 0.62, 0.30, phys_floor=1.0),
        ParamSpec("vth_shift_mv", "mV", 0.0, 4.00, 3.00, -50.0, 50.0,
                  "two_sided", 0.4700, 4.00, 0.55, -0.88, 0.12),
    ]


# Failure mechanisms: which parameters a defect actually moves, and with what
# relative weight. Weights are multipliers on the excess drift.
FAILURE_MECHANISMS: dict[str, dict[str, float]] = {
    "JUNCTION_LEAKAGE":   {"iddq_ua": 1.00, "leakage_na": 1.00, "supply_current_ma": 0.55},
    "OXIDE_TRAP_NBTI":    {"vth_shift_mv": 1.00, "prop_delay_ns": 0.85, "iddq_ua": 0.30},
    "INTERCONNECT_RC":    {"prop_delay_ns": 1.00, "supply_current_ma": 0.60},
    "CONTAMINATION_IONIC": {"leakage_na": 1.00, "iddq_ua": 0.75},
}


# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

@dataclass
class GeneratorConfig:
    seed: int = 26170

    # Structure
    n_lots: int = 240
    parts_per_lot: int = 500          # >= 30 required by AEC-Q001
    checkpoints_h: tuple[float, ...] = (0.0, 24.0, 96.0, 168.0)
    board_rows: int = 8
    board_cols: int = 8

    # Cross-parameter correlation. The factor-1 loadings are scaled to hit this
    # target for corr(iddq, leakage), so the assumption can be swept rather than
    # asserted. See sweep_correlation.py and the README: Type III separability
    # is a direct function of how collinear the leakage family is, and this
    # value was originally chosen to make Type III work, which is exactly the
    # kind of reverse-engineering that deserves a sensitivity analysis.
    leakage_corr_target: float = 0.93

    # Arrhenius
    ea_ev: float = 0.7
    t_stress_c: float = 125.0
    t_use_c: float = 55.0

    # Hierarchical model
    lambda_lot_log_sd: float = 0.20   # lot effect on log(lambda)
    lambda_part_log_sd: float = 0.35  # component effect on log(lambda)
    beta_lot_jitter: float = 0.03
    meas_noise_frac_of_part_sd: float = 0.12

    # Contamination: genuine defects (Types I-IV)
    frac_type1: float = 0.0060        # steep drifter
    frac_type2: float = 0.0050        # step defect
    frac_type3: float = 0.0005        # centre-hider, 500 DPPM
    frac_type4: float = 0.0035        # correlation break

    # Traps (labelled GOOD)
    # Type V is split, because "elevated level with no drift" spans two
    # genuinely different cases and the problem statement is explicit that the
    # extreme one is a defect: its worked example is a lot averaging ~10 uA
    # with a part at 45 uA against a datasheet max of 50 uA. Labelling that
    # GOOD would contradict the PS and punish DPAT for doing exactly what the
    # PS asks of it.
    frac_type5a: float = 0.0150       # mildly high, inside normal lot spread -> GOOD
    frac_type5b: float = 0.0025       # far outside the lot, in spec, stable -> DEFECT
    n_type6_lots: int = 6             # lot-wide process shift
    n_type7_boards: int = 10           # fixture / socket artifact

    # Defect shape
    type1_lambda_mult_range: tuple[float, float] = (5.0, 10.0)
    type1_v0_pull_sd: float = 0.8     # steep drifters are drawn low on v0
    type2_jump_range_in_D: tuple[float, float] = (2.5, 5.0)
    type3_band_pct: float = 30.0      # must land within median +/- this many
                                      # percentile points on EVERY parameter
    # How far each centre-hider is pushed toward the box-constrained maximum
    # Mahalanobis distance. This is THE difficulty knob for the hardest class:
    # 1.0 puts the part at the theoretical ceiling (jointly obvious, AUROC 1.0),
    # while lower values leave it inside the good population's joint spread and
    # it escapes. The default spread deliberately produces a mix, because a
    # class that is caught 100% of the time measures nothing.
    type3_shrink_range: tuple[float, float] = (0.75, 1.00)   # legacy, unused
    # Severity tiers. Without them the ablation table is a step function:
    # L0/L1 catch almost nothing, L3 catches everything, and L4/L5 are
    # decorative. A graded class gives each rung something left to win.
    type3_severity: tuple[tuple[str, float, float, float], ...] = (
        ("severe", 0.92, 1.00, 0.34), ("moderate", 0.80, 0.90, 0.33),
        ("mild", 0.66, 0.78, 0.33))
    type4_severity: tuple[tuple[str, float, float, float], ...] = (
        ("severe", 2.2, 2.8, 0.34), ("moderate", 1.6, 2.0, 0.33),
        ("mild", 1.05, 1.40, 0.33))
    type3_min_active_dims: int = 4
    type4_factor_range: tuple[float, float] = (1.7, 2.7)
    type5a_v0_sd_range: tuple[float, float] = (2.0, 3.0)
    type5b_v0_sd_range: tuple[float, float] = (5.5, 7.5)
    type5_lambda_mult_range: tuple[float, float] = (0.20, 0.50)
    type6_lot_shift_sd: float = 4.0   # in units of the lot-effect sd
    type7_delta_t_c: float = 10.0      # hottest socket temperature excess
    type7_contact_offset_sd: float = 1.2  # socket contact resistance offset

    # Censoring
    frac_pulled_failed: float = 0.0030   # drawn from Type I/II parts
    frac_missing_equipment: float = 0.0040
    n_chamber_trips: int = 8             # (board, checkpoint) pairs lost

    # Safety
    spec_margin_frac: float = 0.03    # keep defects this far inside limits
                                      # (fraction of the limit range)

    enabled_types: tuple[str, ...] = ("I", "II", "III", "IV", "V", "VI", "VII")
    enable_censoring: bool = True

    def to_dict(self) -> dict:
        d = dataclasses.asdict(self)
        d["checkpoints_h"] = list(self.checkpoints_h)
        d["enabled_types"] = list(self.enabled_types)
        d["type3_severity"] = [list(x) for x in self.type3_severity]
        d["type4_severity"] = [list(x) for x in self.type4_severity]
        for k in ("type1_lambda_mult_range", "type2_jump_range_in_D",
                  "type3_shrink_range", "type4_factor_range",
                  "type5a_v0_sd_range", "type5b_v0_sd_range",
                  "type5_lambda_mult_range"):
            d[k] = list(getattr(self, k))
        return d


# --------------------------------------------------------------------------
# Correlation structure
# --------------------------------------------------------------------------

def build_correlation(params: list[ParamSpec]) -> np.ndarray:
    """2-factor correlation matrix. Guaranteed positive definite because the
    idiosyncratic variances 1 - f1^2 - f2^2 are all strictly positive."""
    f1 = np.array([p.f1 for p in params])
    f2 = np.array([p.f2 for p in params])
    idio = 1.0 - f1 ** 2 - f2 ** 2
    if (idio <= 1e-6).any():
        raise ValueError(f"factor loadings leave non-positive idiosyncratic variance: {idio}")
    R = np.outer(f1, f1) + np.outer(f2, f2) + np.diag(idio)
    # numerical symmetrisation
    return (R + R.T) / 2.0


def max_box_mahalanobis(cov: np.ndarray, c: float,
                        active: np.ndarray | None = None) -> tuple[float, np.ndarray]:
    """Largest squared Mahalanobis distance reachable while every standardised
    marginal stays inside [-c, +c], optionally with some coordinates pinned to
    zero.

    Because z^T S^-1 z is convex, its maximum over the box is attained at a
    vertex, so enumerating the 2^p sign patterns is exact (p = 5 here).

    This function is the mathematical core of the Type III construction, and
    it is also what lets us state the *ceiling* honestly: a centre-hider
    cannot be more anomalous than this while remaining univariately central.
    """
    p = cov.shape[0]
    sd = np.sqrt(np.diag(cov))
    corr = cov / np.outer(sd, sd)
    inv = np.linalg.inv(corr)
    if active is None:
        active = np.ones(p, dtype=bool)
    idx = np.where(active)[0]
    best_val, best_z = -1.0, np.zeros(p)
    for signs in itertools.product([-1.0, 1.0], repeat=len(idx)):
        z = np.zeros(p)
        z[idx] = np.array(signs) * c
        val = float(z @ inv @ z)
        if val > best_val:
            best_val, best_z = val, z
    return best_val, best_z


# --------------------------------------------------------------------------
# Generator
# --------------------------------------------------------------------------

DEFECT_TYPES = {
    "GOOD": "Nominal part",
    "I_STEEP_DRIFTER": "Elevated degradation rate, stays inside datasheet limits",
    "II_STEP_DEFECT": "Nominal drift plus a discrete jump between two checkpoints",
    "III_CENTRE_HIDER": "Univariately central on every parameter, anomalous only jointly",
    "IV_CORRELATION_BREAK": "Individually normal, leakage/delay relationship inverted",
    "Va_MILDLY_HIGH_STABLE": ("TRAP. Mildly elevated level inside normal lot "
                              "spread, minimal drift. Not a defect."),
    "Vb_EXTREME_LEVEL": ("DEFECT. Level far outside the lot distribution but "
                         "still inside datasheet limits, minimal drift. This is "
                         "the problem statement's own worked example."),
    "VI_LOT_SHIFT": "TRAP. Whole-lot process shift. Not a part defect.",
    "VII_FIXTURE_ARTIFACT": "TRAP. Socket/board thermal artifact. Not a part defect.",
}

GENUINE_DEFECTS = {"I_STEEP_DRIFTER", "II_STEP_DEFECT", "III_CENTRE_HIDER",
                   "IV_CORRELATION_BREAK", "Vb_EXTREME_LEVEL"}
TRAPS = {"Va_MILDLY_HIGH_STABLE", "VI_LOT_SHIFT", "VII_FIXTURE_ARTIFACT"}


class BurnInGenerator:
    def __init__(self, cfg: GeneratorConfig):
        self.cfg = cfg
        self.params = default_params()
        self.pnames = [p.name for p in self.params]
        self.P = len(self.params)
        self.T = np.array(cfg.checkpoints_h, dtype=float)
        self.nT = len(self.T)

        for p in self.params:
            if not (0.5 <= p.beta <= 1.0):
                raise ValueError(f"beta for {p.name} = {p.beta} outside [0.5, 1.0]")

        self._rescale_factor1(cfg.leakage_corr_target)
        self.R = build_correlation(self.params)
        self.L = np.linalg.cholesky(self.R)

        self.af = arrhenius_af(cfg.ea_ev, cfg.t_use_c, cfg.t_stress_c)
        self.field_years = {float(t): field_years_equivalent(t, self.af) for t in self.T}
        self.t_end = float(self.T[-1])

        # Median drift at the final checkpoint, derived from Arrhenius.
        self.drift_end = np.array([
            p.drift_frac_per_field_year * self.field_years[self.t_end] * p.drift_ref
            for p in self.params
        ])
        self.beta = np.array([p.beta for p in self.params])
        self.lambda0 = self.drift_end / (self.t_end ** self.beta)

        self.v0_mean = np.array([p.v0_mean for p in self.params])
        self.sd_part = np.array([p.v0_sd_part for p in self.params])
        self.sd_lot = np.array([p.v0_sd_lot for p in self.params])
        self.lo = np.array([p.limit_lo for p in self.params])
        self.hi = np.array([p.limit_hi for p in self.params])
        self.margin = (self.hi - self.lo) * cfg.spec_margin_frac
        self.floor = np.array([-np.inf if p.phys_floor is None else p.phys_floor
                               for p in self.params])
        self.log_mask = np.array([p.log_scale for p in self.params])
        # Measurement noise is quoted against the *observed* spread, so for a
        # log-normal parameter it is referenced to the median times the
        # log-sigma rather than to the log-sigma itself.
        self.obs_sd_part = np.where(self.log_mask,
                                    self.v0_mean * self.sd_part, self.sd_part)
        self.sd_eps = self.obs_sd_part * cfg.meas_noise_frac_of_part_sd

        self.sockets_per_board = cfg.board_rows * cfg.board_cols
        self.diag: dict[str, object] = {}

    def _rescale_factor1(self, target_r: float) -> None:
        """Scale every factor-1 loading by a common k so that
        corr(iddq, leakage) hits `target_r`.

            r = k^2 * f1_iddq * f1_leak + f2_iddq * f2_leak

        Scaling the whole factor-1 vector keeps the *shape* of the physical
        story intact -- leaky parts stay fast, high-vth parts stay slow -- and
        only changes how much of each parameter the common process corner
        explains. Idiosyncratic variances are recomputed to keep unit diagonal.
        """
        i, j = self.pnames.index("iddq_ua"), self.pnames.index("leakage_na")
        f1 = np.array([q.f1 for q in self.params])
        f2 = np.array([q.f2 for q in self.params])
        num = target_r - f2[i] * f2[j]
        den = f1[i] * f1[j]
        if num <= 0:
            raise ValueError(f"leakage_corr_target={target_r} unreachable: factor 2 "
                             f"alone already contributes {f2[i] * f2[j]:.3f}")
        k = math.sqrt(num / den)
        idio = 1.0 - (k * f1) ** 2 - f2 ** 2
        if (idio <= 1e-6).any():
            bad = [self.pnames[q] for q in np.where(idio <= 1e-6)[0]]
            raise ValueError(f"leakage_corr_target={target_r} leaves non-positive "
                             f"idiosyncratic variance on {bad}")
        for q, scaled in zip(self.params, k * f1):
            q.f1 = float(scaled)
        self.factor1_scale = k

    # -- RNG streams ------------------------------------------------------
    def _rng(self, stream: int) -> np.random.Generator:
        """Independent stream per concern, so toggling a defect type does not
        shift the good-part draws."""
        return np.random.default_rng([self.cfg.seed, stream])

    def _mvn(self, rng, sd: np.ndarray, n: int) -> np.ndarray:
        """n x P draws from MVN(0, diag(sd) R diag(sd))."""
        z = rng.standard_normal((n, self.P))
        return (z @ self.L.T) * sd

    # -- level composition -------------------------------------------------
    def compose_v0(self, base: np.ndarray, eff: np.ndarray) -> np.ndarray:
        """Combine a baseline level with a random effect.

        Linear parameters add; log-normal parameters multiply. `eff` is already
        scaled by the relevant sd (which is a log-sd for log parameters), so
        both branches take the same input.
        """
        return np.where(self.log_mask, base * np.exp(eff), base + eff)

    def offset_sd(self, v0: np.ndarray, k: np.ndarray) -> np.ndarray:
        """Shift a level by `k` component-sd units, in the parameter's own
        space. This is what every defect injection uses, so a 3-sigma shift
        means the same thing whether the parameter is Gaussian or log-normal."""
        return np.where(self.log_mask, v0 * np.exp(k * self.sd_part),
                        v0 + k * self.sd_part)

    # -- physics helper ---------------------------------------------------
    def socket_temp_accel(self, delta_t_c: float) -> float:
        """How much faster a socket that runs `delta_t_c` hotter degrades.

        Degradation rate scales with the Arrhenius acceleration factor, so a
        hotter socket has its lambda multiplied by AF(T+dT)/AF(T). This is
        what makes the Type VII fixture artifact a *physical* effect rather
        than an arbitrary offset.
        """
        cfg = self.cfg
        af_hot = arrhenius_af(cfg.ea_ev, cfg.t_use_c, cfg.t_stress_c + delta_t_c)
        return af_hot / self.af

    # -- structure --------------------------------------------------------
    def _build_index(self) -> pd.DataFrame:
        cfg = self.cfg
        rows = []
        for l in range(cfg.n_lots):
            for i in range(cfg.parts_per_lot):
                board_in_lot = i // self.sockets_per_board
                sock = i % self.sockets_per_board
                rows.append((
                    f"LOT{l:03d}",
                    l,
                    f"LOT{l:03d}-C{i:04d}",
                    f"LOT{l:03d}-B{board_in_lot:02d}",
                    sock // cfg.board_cols,
                    sock % cfg.board_cols,
                ))
        return pd.DataFrame(rows, columns=[
            "lot_id", "lot_index", "component_id", "board_id",
            "socket_row", "socket_col"])

    # -- good-part core ---------------------------------------------------
    def _draw_good(self, idx: pd.DataFrame):
        """Hierarchical good-part model.

            v0_ip   = mu0_p + a_lp + b_ip
            lam_ip  = lam0_p * exp(g_lp + h_ip - 0.5*(s_lot^2 + s_part^2))
            x_ipt   = v0_ip + lam_ip * t^beta_lp + eps_ipt

        Returns v0 (N x P), lam (N x P), beta_lot (N x P), and the noise
        array (N x T x P). The -0.5*sigma^2 term keeps the *median* lambda
        equal to lam0, so `drift_end` really is the median drift.
        """
        cfg = self.cfg
        N = len(idx)
        lot_index = idx["lot_index"].to_numpy()

        rng_lot = self._rng(1)
        a_lot = self._mvn(rng_lot, self.sd_lot, cfg.n_lots)
        g_lot = self._mvn(rng_lot, np.full(self.P, cfg.lambda_lot_log_sd), cfg.n_lots)
        beta_lot = (self.beta[None, :]
                    + rng_lot.uniform(-cfg.beta_lot_jitter, cfg.beta_lot_jitter,
                                      (cfg.n_lots, self.P)))
        beta_lot = np.clip(beta_lot, 0.5, 1.0)

        rng_part = self._rng(2)
        b_part = self._mvn(rng_part, self.sd_part, N)
        h_part = self._mvn(rng_part, np.full(self.P, cfg.lambda_part_log_sd), N)

        rng_eps = self._rng(3)
        eps = rng_eps.standard_normal((N, self.nT, self.P)) * self.sd_eps

        lot_base = self.compose_v0(self.v0_mean[None, :], a_lot[lot_index])
        v0 = self.compose_v0(lot_base, b_part)
        log_corr = -0.5 * (cfg.lambda_lot_log_sd ** 2 + cfg.lambda_part_log_sd ** 2)
        lam = self.lambda0[None, :] * np.exp(g_lot[lot_index] + h_part + log_corr)
        beta_i = beta_lot[lot_index]
        return v0, lam, beta_i, eps, a_lot, beta_lot, lot_base

    def _trajectory(self, v0, lam, beta_i, eps, accel=None):
        """x_ipt = v0 + lam * accel * t^beta + eps."""
        tp = self.T[None, :, None] ** beta_i[:, None, :]      # N x T x P
        rate = lam[:, None, :]
        if accel is not None:
            rate = rate * accel[:, None, :]
        return v0[:, None, :] + rate * tp + eps

    # -- limit enforcement -------------------------------------------------
    def _fit_inside_limits(self, base: np.ndarray, offset: np.ndarray,
                           t_mask: np.ndarray | None = None) -> np.ndarray:
        """Return the largest s in [0,1] (per part) such that base + s*offset
        stays inside [lo+margin, hi-margin] at every checkpoint in `t_mask`.

        This is how the hard constraint is enforced *by construction*: the
        injected defect is shrunk until it fits, rather than the part being
        filtered out afterwards. `base` and `offset` are (N, T, P).
        """
        lo = (self.lo + self.margin)[None, None, :]
        hi = (self.hi - self.margin)[None, None, :]
        if t_mask is None:
            t_mask = np.ones(self.nT, dtype=bool)
        b = base[:, t_mask, :]
        o = offset[:, t_mask, :]

        with np.errstate(divide="ignore", invalid="ignore"):
            s_hi = np.where(o > 0, (hi - b) / o, np.inf)
            s_lo = np.where(o < 0, (lo - b) / o, np.inf)
        s = np.minimum(np.nanmin(s_hi, axis=(1, 2)), np.nanmin(s_lo, axis=(1, 2)))
        return np.clip(s, 0.0, 1.0)

    # -- assignment --------------------------------------------------------
    def _assign_types(self, idx: pd.DataFrame):
        """Reserve Type VI lots and Type VII boards first, then draw Types
        I-V from the remaining parts so no part carries two labels."""
        cfg = self.cfg
        N = len(idx)
        rng = self._rng(4)
        dtype = np.array(["GOOD"] * N, dtype=object)

        type6_lots = np.array([], dtype=int)
        if "VI" in cfg.enabled_types and cfg.n_type6_lots > 0:
            type6_lots = rng.choice(cfg.n_lots, size=cfg.n_type6_lots, replace=False)
            dtype[np.isin(idx["lot_index"].to_numpy(), type6_lots)] = "VI_LOT_SHIFT"

        type7_boards: list[str] = []
        if "VII" in cfg.enabled_types and cfg.n_type7_boards > 0:
            free = idx.loc[dtype == "GOOD", "board_id"].unique()
            type7_boards = [str(b) for b in
                            rng.choice(free, size=cfg.n_type7_boards, replace=False)]
            dtype[idx["board_id"].isin(type7_boards).to_numpy()] = "VII_FIXTURE_ARTIFACT"

        pool = np.where(dtype == "GOOD")[0]
        rng.shuffle(pool)
        cursor = 0
        wanted = [("I", "I_STEEP_DRIFTER", cfg.frac_type1),
                  ("II", "II_STEP_DEFECT", cfg.frac_type2),
                  ("IV", "IV_CORRELATION_BREAK", cfg.frac_type4),
                  ("V", "Va_MILDLY_HIGH_STABLE", cfg.frac_type5a),
                  ("V", "Vb_EXTREME_LEVEL", cfg.frac_type5b),
                  ("III", "III_CENTRE_HIDER", cfg.frac_type3)]
        for tag, label, frac in wanted:
            if tag not in cfg.enabled_types:
                continue
            k = int(round(frac * N))
            if k == 0:
                continue
            sel = pool[cursor:cursor + k]
            cursor += k
            dtype[sel] = label
        return dtype, type6_lots, type7_boards

    # -- main --------------------------------------------------------------
    def generate(self):
        cfg = self.cfg
        idx = self._build_index()
        N = len(idx)
        lot_index = idx["lot_index"].to_numpy()

        v0, lam, beta_i, eps, a_lot, beta_lot, lot_base = self._draw_good(idx)
        v0_g, lam_g = v0.copy(), lam.copy()          # untouched good baseline
        dtype, type6_lots, type7_boards = self._assign_types(idx)

        accel = np.ones((N, self.P))
        mech_w = np.zeros((N, self.P))               # which params a defect moves
        mechanism = np.array([""] * N, dtype=object)
        severity = np.array([""] * N, dtype=object)
        realized: dict[int, dict] = {}

        def pick_tier(rng, spec):
            names = [x[0] for x in spec]
            wts = np.array([x[3] for x in spec], dtype=float)
            j = int(rng.choice(len(names), p=wts / wts.sum()))
            return names[j], float(rng.uniform(spec[j][1], spec[j][2]))

        # ---------------- Type VI: lot-wide process shift ----------------
        # Applied to v0 so it behaves exactly like an ordinary (but extreme)
        # lot random effect. Dynamic PAT recomputes its median per lot and is
        # therefore blind to it BY DESIGN; a static/global limit is not.
        if len(type6_lots):
            rng = self._rng(11)
            for l in type6_lots:
                mask = lot_index == l
                mech = str(rng.choice(list(FAILURE_MECHANISMS)))
                w = np.array([FAILURE_MECHANISMS[mech].get(n, 0.0) for n in self.pnames])
                k = cfg.type6_lot_shift_sd * (self.sd_lot / np.maximum(self.sd_part, 1e-12))
                k = k * w * float(rng.choice([-1.0, 1.0]))
                v0[mask] = self.offset_sd(v0[mask], k[None, :])
                mechanism[mask] = f"PROCESS_EXCURSION:{mech}"

        # ---------------- Type VII: fixture artifact ---------------------
        # A chamber/socket thermal gradient, modelled from the temperature
        # dependence of the parameters themselves rather than as an arbitrary
        # offset. A socket running dT hotter produces four coupled effects:
        #   (a) degradation accelerates      -> lambda scaled by the ratio of
        #       Arrhenius factors, using the same function as everything else
        #   (b) leakage roughly doubles per 15 C  -> iddq and input leakage
        #       levels multiplied by exp(alpha * dT)
        #   (c) carrier mobility drops       -> propagation delay rises ~0.3%/C
        #   (d) threshold voltage falls      -> vth_shift about -1 mV/C
        #   (e) socket contact resistance    -> a small supply-current offset
        #
        # Note (b) and (c) together are a *correlation break*: the process
        # makes leaky parts FAST, whereas heat makes a part leaky and SLOW. So
        # a fixture artifact is genuinely visible to the multivariate layer,
        # and it should be -- see README, "where this deviates from the spec".
        # What only the spatial layer can do is say the cause is the chamber
        # rather than the component.
        #
        # The effect is applied from the first stressed checkpoint onward, not
        # at 0 h: the incoming measurement is taken on the bench at ambient,
        # before the parts are loaded into the oven. That makes a clean 0 h
        # reading followed by a socket-correlated shift, which is itself
        # diagnostic of fixture rather than part.
        fixture_level = np.zeros((N, self.nT, self.P))
        if type7_boards:
            rng = self._rng(12)
            board = idx["board_id"].to_numpy()
            r = idx["socket_row"].to_numpy()
            c = idx["socket_col"].to_numpy()
            rc = (cfg.board_rows - 1) / 2.0
            cc = (cfg.board_cols - 1) / 2.0
            dist = np.sqrt(((r - rc) / max(rc, 1)) ** 2 + ((c - cc) / max(cc, 1)) ** 2)
            dist = dist / dist.max()
            alpha = math.log(2.0) / 15.0        # leakage doubles per 15 C
            j_iddq = self.pnames.index("iddq_ua")
            j_leak = self.pnames.index("leakage_na")
            j_dly = self.pnames.index("prop_delay_ns")
            j_vth = self.pnames.index("vth_shift_mv")
            j_sup = self.pnames.index("supply_current_ma")
            stressed = self.T > 0
            for b in type7_boards:
                m = np.where(board == b)[0]
                edge_hot = bool(rng.random() < 0.5)
                w_hot = dist[m] if edge_hot else (1.0 - dist[m])
                dt = cfg.type7_delta_t_c * w_hot
                accel[m] *= np.array([self.socket_temp_accel(float(v)) for v in dt])[:, None]
                lvl = np.zeros((len(m), self.P))
                lvl[:, j_iddq] = self.v0_mean[j_iddq] * (np.exp(alpha * dt) - 1.0)
                lvl[:, j_leak] = self.v0_mean[j_leak] * (np.exp(alpha * dt) - 1.0)
                lvl[:, j_dly] = self.v0_mean[j_dly] * 0.003 * dt
                lvl[:, j_vth] = -1.0 * dt
                lvl[:, j_sup] = cfg.type7_contact_offset_sd * w_hot * self.obs_sd_part[j_sup]
                fixture_level[np.ix_(m, np.where(stressed)[0])] += lvl[:, None, :]
                b = str(b)
                mechanism[m] = (f"FIXTURE_THERMAL_GRADIENT:"
                                f"{'edge' if edge_hot else 'centre'}_hot")

        # ---------------- Type Va: mildly high but stable -----------------
        # The level shift is placed along the *natural* process direction
        # (factor 1, the Vth/process corner), not along an arbitrary subset of
        # parameters. That matters more than it looks: shifting only the
        # leakage family while leaving delay and vth where they were would make
        # this trap a correlation break in disguise, i.e. accidentally a
        # Type IV, and a multivariate detector would then be *right* to flag
        # it. Placed along factor 1 the part is simply an extreme but entirely
        # self-consistent process corner: leaky AND fast, exactly the benign
        # high-leakage part proteanTecs describe. Only a level-based univariate
        # rule with a tight limit should ever flag it, and doing so is overkill.
        f1v = np.array([q.f1 for q in self.params])
        sel = np.where(dtype == "Va_MILDLY_HIGH_STABLE")[0]
        if len(sel):
            rng = self._rng(13)
            for i in sel:
                k = float(rng.uniform(*cfg.type5a_v0_sd_range))
                v0[i] = self.offset_sd(v0[i], k * f1v * float(np.sign(f1v[0])))
                lam[i] *= float(rng.uniform(*cfg.type5_lambda_mult_range))
                mechanism[i] = "BENIGN_PROCESS_CORNER"
                realized[int(i)] = {"level_sd_along_factor1": round(k, 3)}

        # ---------------- Type Vb: extreme level, stable ------------------
        # The problem statement's canonical anomaly: a part sitting far outside
        # its lot's distribution while still passing the datasheet limit. It is
        # a DEFECT, and unlike Va it follows a failure-mechanism direction
        # rather than the process corner, because a part that is leaky without
        # being correspondingly fast is not a process corner -- it is a part
        # with a leakage path. Drift stays minimal: the defect is already
        # present at incoming, it does not develop during burn-in. This is the
        # class that Dynamic PAT is supposed to catch, and it is what gives the
        # L1 rung of the ablation something real to do.
        sel = np.where(dtype == "Vb_EXTREME_LEVEL")[0]
        if len(sel):
            rng = self._rng(19)
            for i in sel:
                mech = str(rng.choice(list(FAILURE_MECHANISMS)))
                w = np.array([FAILURE_MECHANISMS[mech].get(n, 0.0) for n in self.pnames])
                k = float(rng.uniform(*cfg.type5b_v0_sd_range))
                v0[i] = self.offset_sd(v0[i], k * w)
                lam[i] *= float(rng.uniform(*cfg.type5_lambda_mult_range))
                mech_w[i] = w
                mechanism[i] = f"STATIC_LEVEL_DEFECT:{mech}"
                realized[int(i)] = {"level_sd": round(k, 3), "mechanism_params":
                                    [self.pnames[j] for j in np.where(w > 0)[0]]}

        # ---------------- Type I: steep drifter --------------------------
        sel = np.where(dtype == "I_STEEP_DRIFTER")[0]
        if len(sel):
            rng = self._rng(14)
            for i in sel:
                mech = str(rng.choice(list(FAILURE_MECHANISMS)))
                w = np.array([FAILURE_MECHANISMS[mech].get(n, 0.0) for n in self.pnames])
                m = float(rng.uniform(*cfg.type1_lambda_mult_range))
                # drawn low on v0 so the extra drift can be absorbed and the
                # part still finishes inside the datasheet limit
                v0[i] = self.offset_sd(v0[i], -cfg.type1_v0_pull_sd * w)
                lam[i] = lam[i] * np.where(w > 0, 1.0 + (m - 1.0) * w, 1.0)
                mech_w[i] = w
                mechanism[i] = f"ACCELERATED:{mech}"
                realized[int(i)] = {"lambda_mult": round(m, 3), "mechanism_params":
                                    [self.pnames[j] for j in np.where(w > 0)[0]]}

        # ---------------- trajectories, and the in-spec guarantee --------
        # x_good is what the part would have measured with no injection.
        # x_inj is the injected version. Anything injected is shrunk toward
        # x_good until every checkpoint sits inside the datasheet limits.
        x_good = self._trajectory(v0_g, lam_g, beta_i, eps)
        x_inj = self._trajectory(v0, lam, beta_i, eps, accel) + fixture_level
        x = x_good.copy()
        moved = np.where(dtype != "GOOD")[0]
        if len(moved):
            # Anchor the in-spec shrink on the part's LOT MEDIAN trajectory, not
            # on the part's own good-part baseline. With log-normal parameters a
            # handful of genuinely good parts sit outside the datasheet limits
            # by chance; if one of those is selected for injection, shrinking
            # toward its own baseline converges on a value that is already out
            # of spec and the guarantee silently fails. The lot median is always
            # comfortably inside, so shrinking toward it cannot. This binds only
            # when the shrink is active, which is rare.
            med_traj = np.zeros((cfg.n_lots, self.nT, self.P))
            for l in range(cfg.n_lots):
                g = np.where((lot_index == l) & (dtype == "GOOD"))[0]
                src = g if len(g) else np.where(lot_index == l)[0]
                med_traj[l] = np.median(x_good[src], axis=0)
            base = med_traj[lot_index[moved]]
            off = x_inj[moved] - base
            s = self._fit_inside_limits(base, off)
            x[moved] = base + s[:, None, None] * off
            for k, i in enumerate(moved):
                if s[k] < 1.0:
                    realized.setdefault(int(i), {})["spec_shrink"] = round(float(s[k]), 4)

        # ---------------- Type II: step defect ---------------------------
        sel = np.where(dtype == "II_STEP_DEFECT")[0]
        if len(sel):
            rng = self._rng(15)
            for i in sel:
                mech = str(rng.choice(list(FAILURE_MECHANISMS)))
                w = np.array([FAILURE_MECHANISMS[mech].get(n, 0.0) for n in self.pnames])
                after = int(rng.integers(1, self.nT))       # jump lands before this index
                jmag = float(rng.uniform(*cfg.type2_jump_range_in_D))
                step = np.zeros((self.nT, self.P))
                step[after:, :] = jmag * self.drift_end * w
                s = float(self._fit_inside_limits(x[i:i + 1], step[None, ...])[0])
                x[i] = x[i] + s * step
                mech_w[i] = w
                mechanism[i] = f"DISCRETE_STEP:{mech}"
                realized[int(i)] = {
                    "jump_between_h": [float(self.T[after - 1]), float(self.T[after])],
                    "jump_size_in_median_drift_units": round(jmag * s, 3),
                    "spec_shrink": round(s, 4),
                    "mechanism_params": [self.pnames[j] for j in np.where(w > 0)[0]]}

        # ---------------- Type IV: correlation break ---------------------
        # The part's factor-1 content is replaced by an inverted version: the
        # delay and vth loadings have their sign flipped, so the part reads as
        # leaky AND slow, a combination the process does not produce. Applied
        # as a constant level offset, so its drift stays perfectly normal.
        sel = np.where(dtype == "IV_CORRELATION_BREAK")[0]
        if len(sel):
            rng = self._rng(16)
            f1 = np.array([p.f1 for p in self.params])
            flip = np.array([-1.0 if n in ("prop_delay_ns", "vth_shift_mv") else 1.0
                             for n in self.pnames])
            for i in sel:
                tier, mag = pick_tier(rng, cfg.type4_severity)
                severity[i] = tier
                score = mag * float(rng.choice([-1.0, 1.0]))
                target_z = score * f1 * flip
                # replace the part's own factor-1 content with the inverted
                # one, rebuilding from its lot baseline so this works for
                # log-normal and linear parameters alike
                want = self.offset_sd(lot_base[i], target_z)
                off = np.tile(want - v0_g[i], (self.nT, 1))
                s = float(self._fit_inside_limits(x[i:i + 1], off[None, ...])[0])
                x[i] = x[i] + s * off
                mechanism[i] = "CORRELATION_INVERSION"
                realized[int(i)] = {"severity": tier, "factor_score": round(score, 3),
                                    "target_z": [round(float(v), 3) for v in target_z],
                                    "spec_shrink": round(s, 4)}

        # ---------------- Type III: centre-hider -------------------------
        type3_report = None
        if (dtype == "III_CENTRE_HIDER").any():
            type3_report = self._inject_centre_hiders(x, idx, dtype, realized, severity)
            mechanism[dtype == "III_CENTRE_HIDER"] = "LATENT_JOINT_INCONSISTENCY"

        # ---------------- physical measurement floor ---------------------
        # Iddq, input leakage and supply current are strictly positive
        # quantities; a tester reports a floor, never a negative value. This
        # binds on roughly 1 part in 30,000 at the extreme low tail and is
        # applied after injection so the empirical covariance used by the
        # Type III construction already reflects it.
        n_floored = int((x < self.floor[None, None, :]).sum())
        x = np.maximum(x, self.floor[None, None, :])
        self.diag["n_floored_measurements"] = n_floored

        # ---------------- censoring --------------------------------------
        status, true_end = self._apply_censoring(x, idx, dtype, mech_w)

        self.diag.update({
            "type3": type3_report,
            "type6_lots": [f"LOT{l:03d}" for l in type6_lots],
            "type7_boards": list(type7_boards),
            "af": self.af,
        })
        return self._assemble(idx, x, status, dtype, mechanism, true_end,
                              realized, severity)

    # ------------------------------------------------------------------
    def _inject_centre_hiders(self, x, idx, dtype, realized, severity):
        """Type III construction.

        For each target part we take the *empirical* within-lot covariance of
        the good population at each checkpoint (so measurement noise and drift
        spread are automatically accounted for), find the direction that
        maximises Mahalanobis distance subject to every standardised marginal
        staying inside the configured percentile band, and place the part
        there. The residual direction is held fixed across checkpoints so the
        part's drift is exactly typical: a centre-hider has to be invisible to
        the trajectory layer too, not just to univariate limits.

        The band/anomaly trade-off is fundamental and is reported rather than
        hidden. A point sitting at the exact median of every parameter has
        Mahalanobis distance zero by definition, so a centre-hider must sit at
        the *edge* of whatever central band we allow it.
        """
        cfg = self.cfg
        rng = self._rng(17)
        sel = np.where(dtype == "III_CENTRE_HIDER")[0]
        lot_index = idx["lot_index"].to_numpy()
        c = math.sqrt(2.0) * _erfinv(2.0 * (0.5 + cfg.type3_band_pct / 100.0) - 1.0)
        report = {"band_pct": cfg.type3_band_pct, "z_cap": round(c, 4), "parts": []}

        for i in sel:
            l = lot_index[i]
            peers = np.where((lot_index == l) & (dtype == "GOOD"))[0]
            # marginal reference = every part in the lot except the other
            # centre-hiders, i.e. exactly what a detector would compute
            lot_ref = np.where((lot_index == l) & (dtype != "III_CENTRE_HIDER"))[0]
            active = np.ones(self.P, dtype=bool)
            n_active = int(rng.integers(cfg.type3_min_active_dims, self.P + 1))
            if n_active < self.P:
                active[rng.choice(self.P, size=self.P - n_active, replace=False)] = False
            names = [q[0] for q in cfg.type3_severity]
            wts = np.array([q[3] for q in cfg.type3_severity], dtype=float)
            j = int(rng.choice(len(names), p=wts / wts.sum()))
            severity[i] = names[j]
            shrink = rng.uniform(cfg.type3_severity[j][1], cfg.type3_severity[j][2],
                                 size=self.P)

            per_cp, d2s, ceilings, pcts = [], [], [], []
            for ti in range(self.nT):
                # direction from the CLEAN good population, so the shape of the
                # anomaly is defined against an uncontaminated reference
                block = x[peers, ti, :]
                ref = x[lot_ref, ti, :]
                cov = np.cov(block, rowvar=False)
                med = np.median(block, axis=0)
                sd = np.sqrt(np.diag(cov))
                corr = cov / np.outer(sd, sd)
                inv = np.linalg.inv(corr)
                d2_max, z_star = max_box_mahalanobis(cov, c, active)
                z = z_star * shrink

                # placement by EMPIRICAL quantile of the whole lot, not by
                # med + z*sd. The lot distribution is close to Gaussian but not
                # exactly so (lambda is log-normal, so later checkpoints carry a
                # slight right skew), and a Gaussian placement therefore misses
                # the intended percentile by a few points -- which is precisely
                # the assertion Type III has to satisfy. Quantile placement
                # makes the percentile exact by construction; the whole lot is
                # used because that is the reference a detector actually sees.
                pct = 0.5 * (1.0 + np.array([math.erf(v / math.sqrt(2.0)) for v in z]))
                # np.quantile interpolates linearly; scipy's percentileofscore
                # uses mean rank. On 500 parts they can disagree by ~0.2 of a
                # percentile point, which is enough to breach the band by a
                # hair. Hold back half a point so the assertion tests the
                # construction rather than the tie-breaking convention.
                lo_p = (50.0 - cfg.type3_band_pct + 0.5) / 100.0
                hi_p = (50.0 + cfg.type3_band_pct - 0.5) / 100.0
                pct = np.clip(pct, lo_p, hi_p)
                vals = np.array([np.quantile(ref[:, j], pct[j]) for j in range(self.P)])

                z_real = (vals - med) / sd
                d2s.append(float(z_real @ inv @ z_real))
                ceilings.append(float(d2_max))
                pcts.append([round(float(v) * 100, 2) for v in pct])
                per_cp.append(vals)

            off = np.array(per_cp) - x[i]
            s = float(self._fit_inside_limits(x[i:i + 1], off[None, ...])[0])
            if s < 1.0:
                # Fail loudly: silently shrinking the hardest construction
                # would produce a dataset that only looks right.
                raise RuntimeError(
                    f"Type III part {idx['component_id'].iloc[int(i)]} needed spec "
                    f"shrink {s:.3f}; a centre-hider should be nowhere near a limit.")
            x[i] = np.array(per_cp)

            realized[int(i)] = {
                "maha_d2_by_checkpoint": [round(v, 3) for v in d2s],
                "maha_d2_box_ceiling": [round(v, 3) for v in ceilings],
                "severity": names[j],
                "active_dims": [self.pnames[k] for k in np.where(active)[0]],
                "target_percentiles": pcts[0],
                "band_pct": cfg.type3_band_pct}
            report["parts"].append({
                "component_id": str(idx["component_id"].iloc[int(i)]),
                "severity": names[j],
                "d2": [round(v, 3) for v in d2s],
                "d2_ceiling": [round(v, 3) for v in ceilings]})
        return report

    # ------------------------------------------------------------------
    def _apply_censoring(self, x, idx, dtype, mech_w):
        """Three measurement states, kept distinct in the schema.

        MEASURED          a real value is present.
        PULLED_FAILED     the part failed hard between 96 h and 168 h and was
                          removed from the oven, so there is no 168 h reading.
                          Its *latent* 168 h value is out of spec, which is why
                          it failed, and is recorded in ground truth only.
        MISSING_EQUIPMENT a chamber trip or tester fault lost the reading for a
                          reason that has nothing to do with the part. The true
                          value exists and is recorded in ground truth, so
                          imputation can actually be scored.

        MISSING_EQUIPMENT is deliberately allowed to hit good parts at 168 h as
        well, so that "no 168 h value" is not by itself a label leak.
        """
        cfg = self.cfg
        N = len(idx)
        status = np.full((N, self.nT), "MEASURED", dtype=object)
        true_end = np.full((N, self.P), np.nan)
        if not cfg.enable_censoring:
            return status, true_end

        rng = self._rng(18)
        end = self.nT - 1
        two_sided = np.array([p.direction == "two_sided" for p in self.params])

        # ---- hard failures, drawn from the steep drifters and step defects
        cand = np.where(np.isin(dtype, ["I_STEEP_DRIFTER", "II_STEP_DEFECT"]))[0]
        k = min(len(cand), int(round(cfg.frac_pulled_failed * N)))
        pulled = rng.choice(cand, size=k, replace=False) if k else np.array([], int)
        for i in pulled:
            w = mech_w[i]
            active = w > 0
            if not active.any():
                active = np.ones(self.P, dtype=bool)
            latent = x[i, end].copy()
            over = (self.hi - self.lo) * rng.uniform(0.05, 0.30, size=self.P)
            # breach the limit on the parameters this failure mechanism drives
            up = np.where(two_sided, x[i, end] >= x[i, 0], True)
            breach = np.where(up, self.hi + over, self.lo - over)
            latent[active] = breach[active]
            true_end[i] = latent
            status[i, end] = "PULLED_FAILED"
            x[i, end, :] = np.nan

        # ---- chamber trips: a whole board loses one checkpoint
        boards = idx["board_id"].to_numpy()
        ub = np.unique(boards)
        for _ in range(cfg.n_chamber_trips):
            b = rng.choice(ub)
            ti = int(rng.integers(1, self.nT))
            for i in np.where((boards == b) & (status[:, ti] == "MEASURED"))[0]:
                if ti == end:
                    true_end[i] = x[i, end]
                status[i, ti] = "MISSING_EQUIPMENT"
                x[i, ti, :] = np.nan

        # ---- sporadic tester faults on individual parts
        k = int(round(cfg.frac_missing_equipment * N))
        for i in rng.choice(N, size=k, replace=False):
            ti = int(rng.integers(0, self.nT))
            if status[i, ti] != "MEASURED":
                continue
            if ti == end:
                true_end[i] = x[i, end]
            status[i, ti] = "MISSING_EQUIPMENT"
            x[i, ti, :] = np.nan

        return status, true_end

    # ------------------------------------------------------------------
    def _assemble(self, idx, x, status, dtype, mechanism, true_end, realized,
                  severity):
        N = len(idx)
        rec = idx.loc[idx.index.repeat(self.nT)].reset_index(drop=True)
        rec["checkpoint_h"] = np.tile(self.T, N)
        rec["field_years_equiv"] = rec["checkpoint_h"].map(
            lambda t: round(self.field_years[float(t)], 4))
        rec["measurement_status"] = status.reshape(-1)
        for j, name in enumerate(self.pnames):
            rec[name] = x[:, :, j].reshape(-1)
        rec = rec.drop(columns=["lot_index"])

        gt = idx[["component_id", "lot_id", "board_id"]].copy()
        gt["defect_type"] = dtype
        gt["is_defective"] = np.isin(dtype, sorted(GENUINE_DEFECTS))
        gt["is_trap"] = np.isin(dtype, sorted(TRAPS))
        gt["failure_mechanism"] = mechanism
        gt["severity"] = severity
        gt["censor_status_168h"] = status[:, -1]
        for j, name in enumerate(self.pnames):
            gt[f"true_v168_{name}"] = true_end[:, j]
        gt["injection_detail"] = [json.dumps(realized.get(i, {}), default=_jsonable)
                                  for i in range(N)]
        return rec, gt


def _jsonable(o):
    if isinstance(o, (np.integer,)):
        return int(o)
    if isinstance(o, (np.floating,)):
        return float(o)
    if isinstance(o, np.ndarray):
        return o.tolist()
    return str(o)


def _erfinv(y: float) -> float:
    """Inverse error function, so the percentile band -> z conversion does not
    require scipy at generation time."""
    from math import log, sqrt
    a = 0.147
    ln1 = log(1 - y * y)
    t1 = 2 / (math.pi * a) + ln1 / 2
    x = math.copysign(sqrt(sqrt(t1 * t1 - ln1 / a) - t1), y)
    # two Newton refinements
    for _ in range(3):
        err = math.erf(x) - y
        x -= err / (2 / math.sqrt(math.pi) * math.exp(-x * x))
    return x


# --------------------------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--seed", type=int, default=GeneratorConfig.seed)
    ap.add_argument("--out", type=Path, default=Path("data"))
    ap.add_argument("--lots", type=int, default=GeneratorConfig.n_lots)
    ap.add_argument("--parts-per-lot", type=int, default=GeneratorConfig.parts_per_lot)
    ap.add_argument("--types", type=str, default="I,II,III,IV,V,VI,VII",
                    help="comma separated defect types to enable (staging aid)")
    ap.add_argument("--type3-band", type=float,
                    default=GeneratorConfig.type3_band_pct,
                    help="percentile half-band Type III must stay inside")
    ap.add_argument("--leakage-corr", type=float,
                    default=GeneratorConfig.leakage_corr_target,
                    help="target corr(iddq, leakage); rescales the factor model")
    ap.add_argument("--no-censoring", action="store_true")
    args = ap.parse_args()

    cfg = GeneratorConfig(
        seed=args.seed,
        n_lots=args.lots,
        parts_per_lot=args.parts_per_lot,
        enabled_types=tuple(t.strip() for t in args.types.split(",") if t.strip()),
        enable_censoring=not args.no_censoring,
        leakage_corr_target=args.leakage_corr,
        type3_band_pct=args.type3_band,
    )
    if cfg.parts_per_lot < 30:
        raise SystemExit("AEC-Q001 requires at least 30 parts per lot for limit estimation")

    gen = BurnInGenerator(cfg)
    meas, gt = gen.generate()

    out = args.out
    out.mkdir(parents=True, exist_ok=True)
    # Tester reporting resolution. Real ATE reports a handful of significant
    # digits, not float64, and rounding here also keeps the CSV a sane size.
    meas = meas.round({n: 4 for n in gen.pnames})
    meas.to_csv(out / "burnin_measurements.csv", index=False)
    meas.to_csv(out / "burnin_measurements.csv.gz", index=False,
                compression="gzip")
    gt.to_csv(out / "ground_truth.csv", index=False)

    meta = {
        "config": cfg.to_dict(),
        "parameters": [dataclasses.asdict(p) for p in gen.params],
        "failure_mechanisms": FAILURE_MECHANISMS,
        "defect_type_glossary": DEFECT_TYPES,
        "derived": {
            "acceleration_factor": gen.af,
            "field_years_by_checkpoint": {str(k): v for k, v in gen.field_years.items()},
            "median_drift_at_final_checkpoint": dict(zip(gen.pnames, gen.drift_end.tolist())),
            "lambda0": dict(zip(gen.pnames, gen.lambda0.tolist())),
            "factor1_scale": gen.factor1_scale,
            "correlation_matrix": gen.R.tolist(),
            "correlation_labels": gen.pnames,
            "type6_lots": gen.diag["type6_lots"],
            "type7_boards": gen.diag["type7_boards"],
            "type3_report": gen.diag["type3"],
        },
    }
    plain = json.loads(json.dumps(meta, default=_jsonable))
    (out / "config.json").write_text(json.dumps(plain, indent=2))
    import yaml   # deliberately not wrapped: a run whose config cannot be
                  # written is not a reproducible run, and should fail loudly
    (out / "config.yaml").write_text(yaml.safe_dump(plain, sort_keys=False))

    h = hashlib.sha256((out / "burnin_measurements.csv").read_bytes()).hexdigest()[:16]
    print(f"lots={cfg.n_lots} parts={len(gt)} rows={len(meas)} AF={gen.af:.2f} "
          f"field_years@168h={gen.field_years[gen.t_end]:.3f}")
    print(gt["defect_type"].value_counts().to_string())
    print(f"measurements sha256[:16]={h}")


if __name__ == "__main__":
    main()
