"""Export REAL pipeline output for the QA inspector demo.

Nothing here is synthesised for the demo. Every value is read from the frozen
dataset or from results/ as produced by the committed pipeline, and every
explanation is generated by the same explain/ code that writes the PDF
disposition reports. The ground-truth block is included only so the demo can
reveal the answer AFTER the inspector has decided; it is never used to produce
a tier, a score, or an explanation.

Run after the full pipeline:  python make_demo_data.py
"""
from __future__ import annotations

import json
import subprocess
import time
from pathlib import Path

import numpy as np
import pandas as pd

from explain.decision import ACTIONS, DecisionPolicy
from explain.evidence import Evidence
from explain.rules import REASON_TEXT, UNITS, PartExplanation

# Test lots chosen for archetype coverage, not for flattering results:
# between them they carry every injected type including a 64-part Type VII
# fixture cluster on LOT238.
DEMO_LOTS = ["LOT192", "LOT198", "LOT238"]
OUT = Path("demo/inspector_data.json")


def _f(v):
    """JSON-safe float: NaN/inf -> None, else round to 6 sf."""
    if v is None:
        return None
    v = float(v)
    return None if not np.isfinite(v) else round(v, 6)


def main() -> None:
    t0 = time.time()
    e = Evidence()
    pol = DecisionPolicy(e)
    pool = e.scores["CUM_C4"] >= pol.thr_review["CUM_C4"]
    cps = list(e.checkpoints)
    spec = {q["name"]: q for q in e.ds.cfg["parameters"]}

    try:
        commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                                capture_output=True, text=True).stdout.strip()
    except Exception:
        commit = "unknown"

    out = {
        "meta": {
            "dataset": e.ds.cfg.get("version", "dataset"),
            "commit": commit,
            "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "lots": DEMO_LOTS,
            "split_note": (f"All {len(DEMO_LOTS)} lots are TEST lots "
                           f"({e.split.test[0]}-{e.split.test[-1]}); no detector "
                           "was fitted on any part shown here."),
            "review_threshold_budget_%": 2.0,
            "watch_threshold_budget_%": 7.0,
        },
        "params": [{"name": p, "unit": UNITS[p], "lo": _f(e.limits[p][0]),
                    "hi": _f(e.limits[p][1]),
                    "direction": spec[p]["direction"]} for p in e.params],
        "checkpoints": cps,
        "reason_text": REASON_TEXT,
        "actions": ACTIONS,
        "lots": {},
    }

    for lot in DEMO_LOTS:
        ids = [c for c in e.gt.index[e.lot == lot]]
        stats = {}
        for p in e.params:
            stats[p] = {}
            for t in cps:
                st = e.lot_stats(lot, t).loc[p]
                med, sg = float(st["median"]), float(st["sigma_mad"])
                stats[p][str(int(t))] = {
                    "median": _f(med), "sigma_mad": _f(sg),
                    "sigma_iqr": _f(st["sigma_iqr"]), "n": int(st["n"]),
                    # the AEC-Q001 dynamic PAT band actually used by L1
                    "pat_lo": _f(max(med - 6 * sg, e.limits[p][0])),
                    "pat_hi": _f(min(med + 6 * sg, e.limits[p][1])),
                }
        parts = []
        for k, cid in enumerate(ids):
            x = PartExplanation(e, pol, cid, pool)
            vals, status = {}, {}
            for p in e.params:
                vals[p] = [_f(e.wide.loc[cid, (p, t)]) for t in cps]
            m = e.ds.meas[e.ds.meas["component_id"] == cid]
            status = (m.sort_values("checkpoint_h")["measurement_status"]
                      .tolist())
            mb = {}
            for p in e.params:
                if cid in e.mb_point.index:
                    mb[p] = {"point": _f(e.mb_point.loc[cid, p]),
                             "upper": _f(e.mb_upper.loc[cid, p]),
                             "lsafe": _f(e.l_safe[p].get(cid, np.nan))}
            g = e.gt.loc[cid]
            parts.append({
                "id": cid,
                "board": str(x.meta["board_id"]),
                "row": int(x.meta["socket_row"]), "col": int(x.meta["socket_col"]),
                "v": vals, "status": status,
                "tier": x.tier, "primary": x.primary,
                "secondary": x.secondary or None,
                "score": _f(e.scores.loc[cid, "CUM_C4"]),
                "d2": _f(x.d2), "d2_p99": _f(x.d2_p99),
                "mb": mb,
                "lines": [[a, b] for a, b in x.lines],
                # mechanism dicts -> "hypothesis [confidence]"; str(dict)
                # used to leak the raw Python repr onto the screen
                "hypotheses": [f"{h['hypothesis']} [{h['confidence']}]"
                               for h in x.hypotheses],
                # revealed only after the inspector decides; never an input
                "truth": {"defect_type": str(g["defect_type"]),
                          "is_defective": bool(e.y[cid]),
                          # NaN is truthy, so `or ""` rendered "nan"
                          "severity": "" if pd.isna(g.get("severity")) else str(g["severity"]),
                          "mechanism": "" if pd.isna(g.get("failure_mechanism"))
                          else str(g["failure_mechanism"])},
            })
            if (k + 1) % 100 == 0:
                print(f"  {lot}: {k+1}/{len(ids)}  ({time.time()-t0:.0f}s)",
                      flush=True)
        tiers = pd.Series([p["tier"] for p in parts]).value_counts().to_dict()
        out["lots"][lot] = {"stats": stats, "parts": parts,
                            "tier_counts": {k: int(v) for k, v in tiers.items()}}
        print(f"{lot}: {len(parts)} parts, tiers {tiers}", flush=True)

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(json.dumps(out, separators=(",", ":")), encoding="utf-8")
    mb_size = OUT.stat().st_size / 1e6
    print(f"\nwrote {OUT}  ({mb_size:.2f} MB)  in {time.time()-t0:.0f}s")


if __name__ == "__main__":
    main()
